### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by mkyl**
Added navigation drawer to app. Switched many actions to use fragments instead of activities. Added management for installed beacons.

In navigation menu only "home", "beacons" and "about" are implemented.

### CODE REVIEW

**Comment by mkyl** [comment]
Oh also, switched to Room ORM! Resolves #3

**Comment by mkyl** [comment]
Commit 5a3d54a08622c400579f4d5f01d093994cb8f4ca Fixes #7

**Review by jelcaf — APPROVED** [review]
giphy-downsized

**Comment by mkyl** [comment]
High five gif

**Pull request merged**
